[pytest]
testpaths = tests
markers =
    ui: marks tests as UI tests
    api: marks test as API tests

python_files = test_*.py

# Default options
addopts =
    --alluredir=./reports/allure-results
    --headed
    -v

